### ISSUE TITLE
感觉什么都弄好了，还是没网

### ISSUE THREAD

**Issue by zcmi** [wmyfelix/HttpCanary-SSL-Magisk#4]
系统是MIUI12.5稳定版。好不容易找到个能自己弹出root权限的版本，但是还是无网

![Screenshot_2021-11-04-15-27-06-126_com android settings](https://user-images.githubusercontent.com/24654015/140273921-51cf5732-232a-463c-9512-7929554a4ee9.jpg)
![IMG_20211104_152643](https://user-images.githubusercontent.com/24654015/140273927-932418c8-1bbc-4dff-852a-f737622749b8.jpg)
![IMG_20211104_152602](https://user-images.githubusercontent.com/24654015/140273928-eb0ba442-f1dd-4c67-8706-0ab5a127b742.jpg)
![IMG_20211104_152537](https://user-images.githubusercontent.com/24654015/140273930-3227fa39-c492-40cc-9502-9117cd9976d2.jpg)
![IMG_20211104_152441](https://user-images.githubusercontent.com/24654015/140273933-6b051bd6-74e1-4297-bfed-95b956f05ca6.jpg)
![Screenshot_2021-11-04-15-00-11-858_com guoshi httpcanary premium](https://user-images.githubusercontent.com/24654015/140273937-8dd1fac6-2f0f-496b-b609-da31e9e29e94.jpg)

**Comment by mingww64** [comment]
仅需要VPN权限，不需要root权限。
确保安装本模块前  
  * 未安装其他版本Httpcanary应用  
  * 系统未信任其它Httpcanary证书  

安装本模块后  
  * 未清除Httpcanary应用数据

**Comment by zcmi** [comment]
有安装过其他版本的httpcanary，但是已经卸载干净了，还是不行，应该是我的原因，不过我已经用ios的stream解决了，谢谢你
